// Copyright (C) 2026, Ava Labs, Inc.
// See the file LICENSE for licensing terms.

use std::path::Path;

use foundry_compilers::artifacts::Error as SolcError;

use crate::{MacroOriginalLocation, MacroRules, span_utils::ExpandedOffset};

#[cfg(test)]
pub static TEST_COMPILER_OUTPUT: std::sync::Mutex<Vec<String>> = std::sync::Mutex::new(Vec::new());

/// Describes where a Solc error's primary span originates after walking the offset adjustments.
pub enum ErrorSource {
    /// The span falls inside bytes that were inserted by a macro rule.
    ///
    /// `name` is the macro rule that generated the code, if one was registered via
    /// [`AdjustmentEntry::with`](crate::AdjustmentEntry::with). `loc` is the original source
    /// location to attribute the error to, if one was provided.
    Macro { name: Option<String>, loc: Option<MacroOriginalLocation> },
    /// The span falls in original (non-macro-generated) source. `loc` is the byte offset in
    /// the original, unmodified file after reversing any prior macro expansions.
    RawSource { loc: usize },
}

/// Remaps compiler error line numbers in `e` from macro-expanded coordinates back to the
/// original source, or replaces the message with a macro-error notice if the error points
/// into macro-generated code.
///
/// `loc.file` is used directly as the lookup key because foundry-compilers calls
/// `strip_prefix(project_root)` on the compiler input *before* the preprocessor runs, so
/// the paths stored in `offset_adjustments` are in the same form (relative or absolute) as
/// the paths Solc reports in `source_location.file`.
///
/// Attribution and remapping are driven by `source_location.start`, the byte offset Solc
/// reports for the primary span.
pub fn correct_fmt_msg(
    macros: &MacroRules,
    e: &mut SolcError,
    project_root: &Path,
) -> eyre::Result<()> {
    let Some(ref loc) = e.source_location else { return Ok(()) };
    if loc.start < 0 {
        return Ok(());
    }
    let source = Path::new(&loc.file);
    let expanded_start =
        usize::try_from(loc.start).expect("loc.start is non-negative, checked above");

    let error_source =
        macros.with_offset_adjustments(|adjustments| -> eyre::Result<ErrorSource> {
            if let Some(adj) = adjustments
                .find_macro_adjustment_by_offset(source, ExpandedOffset::new(expanded_start))?
            {
                Ok(ErrorSource::Macro {
                    name: adj.macro_name.clone(),
                    loc: adj.original_location.clone(),
                })
            } else {
                let original_start =
                    adjustments.get_original_offset(source, ExpandedOffset::new(expanded_start))?;
                Ok(ErrorSource::RawSource { loc: original_start.get() })
            }
        })?;

    match error_source {
        ErrorSource::Macro { name, loc } => {
            let short = match &name {
                Some(name) => format!("error in code generated by macro '{}': {}", name, e.message),
                None => format!("error in macro-generated code: {}", e.message),
            };
            let fmt = match (name, loc.as_ref()) {
                (Some(_), Some(orig)) => format_macro_fmt_msg(orig, &short, project_root),
                _ => short.clone(),
            };
            e.message = short;
            e.formatted_message = Some(fmt);
        }
        ErrorSource::RawSource { loc: original_start } if original_start != expanded_start => {
            e.formatted_message =
                Some(render_remapped_frame(source, original_start, &e.message, project_root));
        }
        ErrorSource::RawSource { .. } => {}
    }
    Ok(())
}

/// Returns `(line, col)` — both 1-based — for `offset` in `content`, or `None` if any
/// arithmetic overflows (only possible for astronomically large files).
fn offset_to_line_col(content: &str, offset: usize) -> Option<(usize, usize)> {
    let offset = offset.min(content.len());
    let before = &content[..offset];
    let line = before.bytes().filter(|&b| b == b'\n').count().checked_add(1)?;
    let line_start = match before.rfind('\n') {
        Some(i) => i.checked_add(1)?,
        None => 0,
    };
    let col = offset.checked_sub(line_start)?.checked_add(1)?;
    Some((line, col))
}

/// Builds a Solc-style formatted error message pointing at `original_offset` in `source`.
///
/// Reads the source file from disk (the original, unmodified version) to extract the
/// relevant source line for the frame. Falls back to the bare message if the file cannot
/// be read or the line is out of range.
fn render_remapped_frame(
    source: &Path,
    original_offset: usize,
    message: &str,
    project_root: &Path,
) -> String {
    let abs = if source.is_absolute() { source.to_path_buf() } else { project_root.join(source) };
    let Ok(content) = std::fs::read_to_string(&abs) else {
        return message.to_string();
    };
    let Some((line, col)) = offset_to_line_col(&content, original_offset) else {
        return message.to_string();
    };
    let arrow = format!(" --> {}:{}:{}:", source.display(), line, col);
    let width = line.to_string().len();
    let sep = format!("{:width$} |", "");
    let Some(line_idx) = line.checked_sub(1) else {
        return message.to_string();
    };
    match content.lines().nth(line_idx) {
        Some(line_text) => {
            let framed = format!("{line:>width$} | {line_text}");
            format!("{message}\n{arrow}\n{sep}\n{framed}\n{sep}")
        }
        None => format!("{message}\n{arrow}"),
    }
}

/// Formats a macro attribution error in the new-style Solc format:
///
/// ```text
/// error in code generated by macro 'name': <message>
///  --> /path/to/file.sol:LINE:COL:
///   |
/// N | <source line>
///   |
/// ```
///
/// Falls back to `short_msg` alone if the source line cannot be read.
fn format_macro_fmt_msg(
    orig: &MacroOriginalLocation,
    short_msg: &str,
    project_root: &Path,
) -> String {
    let abs_file =
        if orig.file.is_absolute() { orig.file.clone() } else { project_root.join(&orig.file) };
    let source_line = std::fs::read_to_string(&abs_file).ok().and_then(|content| {
        orig.line.checked_sub(1).and_then(|idx| content.lines().nth(idx)).map(|l| l.to_string())
    });
    let arrow = format!(" --> {}:{}:{}:", orig.file.display(), orig.line, orig.col);
    let width = orig.line.to_string().len();
    let sep = format!("{:width$} |", "");
    match source_line {
        Some(line_text) => {
            let framed = format!("{:>width$} | {}", orig.line, line_text);
            format!("{short_msg}\n{arrow}\n{sep}\n{framed}\n{sep}")
        }
        None => format!("{short_msg}\n{arrow}"),
    }
}

#[cfg(test)]
mod tests {
    use solar::sema::{Gcx, hir::ContractKind};

    use super::offset_to_line_col;
    use crate::{Macro, MacroOriginalLocation, PreprocessingData, span_utils::OriginalOffset};

    /// Strips ANSI escape sequences from `s` so assertions can match plain text.
    fn strip_ansi(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut chars = s.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\x1b' && chars.peek() == Some(&'[') {
                chars.next(); // consume '['
                for c2 in chars.by_ref() {
                    if c2 == 'm' {
                        break;
                    }
                }
            } else {
                out.push(c);
            }
        }
        out
    }

    const TEST_SOURCE_VALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return 42; }
    }
    "#;

    const TEST_SOURCE_INVALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return "42"; }
    }
    "#;

    /// Source whose one-line function body is replaced by the `replace_body` macro with a
    /// multi-line block that introduces a type error. The `// #[replace_body]` trigger sits on
    /// line 4 (col 9) and the body to replace is on line 5.
    const TEST_SOURCE_REPLACE: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[replace_body]
        function original() internal pure returns (uint256) { return 1; }
    }
    "#;

    /// Source in which the `remove_block` macro deletes the `// #[remove_me]` comment and the
    /// entire `toRemove()` function (lines 4-7). The type error is in `broken()` on original
    /// line 9, which the removal shifts up to expanded line 5; error reporting must remap it back.
    const TEST_SOURCE_REMOVE: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[remove_me]
        function toRemove() internal pure returns (uint256) {
            return 1;
        }
        uint256 constant KEEP = 7;
        function broken() internal pure returns (uint256) { return "bad"; }
    }
    "#;

    fn make_macro(fail: bool) -> Macro {
        if fail { insert_foo_fail } else { insert_foo }
    }

    /// Returns the path of the source file that declares `library Foo`, if present.
    fn foo_source_path(data: &PreprocessingData<'_>) -> Option<std::path::PathBuf> {
        data.input
            .iter()
            .find(|(_, s)| s.content.as_str().contains("library Foo"))
            .map(|(p, _)| p.clone())
    }

    /// Replaces `original()`'s one-line body `{ return 1; }` with a multi-line block whose body
    /// returns a string literal (a `uint256` type error). Because the replacement spans more
    /// lines than it removes, the error lands *inside* the macro-generated span and must be
    /// attributed to the macro rather than remapped to original source.
    fn replace_body(
        _ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        const BODY: &str = "{ return 1; }";
        let Some(path) = foo_source_path(data) else { return Ok(()) };
        let (range, loc) = {
            let content = data.input.get(&path).unwrap().content.as_str();
            let Some(start) = content.find(BODY) else { return Ok(()) };
            let trigger = content.find("// #[replace_body]").unwrap_or(start);
            let (line, col) =
                offset_to_line_col(content, trigger).expect("line/col overflow impossible in test");
            let loc = MacroOriginalLocation { file: path.clone(), line, col };
            let end = start.checked_add(BODY.len()).expect("offset overflow impossible in test");
            (OriginalOffset::new(start)..OriginalOffset::new(end), loc)
        };
        let replacement = "{\n        return \"bad\";\n    }";
        data.entry(&path, replacement)
            .expect("Test failed")
            .with("replace_body", Some(loc))
            .replace(range)
            .expect("replace failed in test");
        Ok(())
    }

    /// Removes the `// #[remove_me]` comment and the whole `toRemove()` function, deleting four
    /// lines and shifting everything below it up. Used to exercise line-number remapping of a
    /// compiler error that lives in surviving original source below a removal.
    fn remove_block(
        _ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        let Some(path) = foo_source_path(data) else { return Ok(()) };
        let range = {
            let content = data.input.get(&path).unwrap().content.as_str();
            let Some(start) = content.find("        // #[remove_me]") else { return Ok(()) };
            let Some(end) = content.find("        uint256 constant KEEP") else { return Ok(()) };
            OriginalOffset::new(start)..OriginalOffset::new(end)
        };
        data.entry(&path, "")
            .expect("Test failed")
            .with("remove_block", None)
            .replace(range)
            .expect("Test failed");
        Ok(())
    }

    fn insert_foo(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        insert_in_foo(ctx, data, "insert_foo", "42")
    }

    fn insert_foo_fail(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        insert_in_foo(ctx, data, "insert_foo_fail", r#""not a number""#)
    }

    fn insert_arrow_literal(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        insert_in_foo(ctx, data, "insert_arrow_literal", r#""a --> b""#)
    }

    fn insert_in_foo(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
        macro_name: &str,
        return_expr: &'static str,
    ) -> foundry_compilers::error::Result<()> {
        for contract in ctx.hir.contracts() {
            if contract.kind != ContractKind::Library || contract.name.name.as_str() != "Foo" {
                continue;
            }
            let Some(source) = ctx.sources.get(contract.source) else { continue };
            let Some(path) = source.file.name.as_real() else { continue };
            if !data.input.contains_key(path) {
                continue;
            }

            let start = (contract.span.lo().0 - source.file.start_pos.0) as usize;
            let (after_open_brace, original_loc) = {
                let content = data.input.get(path).unwrap().content.as_str();
                let Some(rel) = content[start..].find('{') else { continue };
                // Use the trigger comment as the attribution location, falling back to the
                // library declaration if the comment is not found.
                let trigger_offset = content.find("// #[insert_foo]").unwrap_or(start);
                let (line, col) = offset_to_line_col(content, trigger_offset)
                    .expect("line/col overflow impossible in test");
                let loc = MacroOriginalLocation { file: path.to_path_buf(), line, col };
                let after = start
                    .checked_add(rel)
                    .and_then(|v| v.checked_add(1))
                    .expect("offset overflow impossible in test");
                (OriginalOffset::new(after), loc)
            };

            let func = format!(
                "\n    function inserted() internal pure returns (uint256) {{\n        return {return_expr}; }}\n",
            );
            data.entry(path, &func)
                .expect("Test failed")
                .with(macro_name, Some(original_loc))
                .insert(after_open_brace)
                .expect("Test failed");
        }
        Ok(())
    }

    fn compile_with_macro(source: &str, fail: bool) -> eyre::Result<()> {
        compile_source_with(source, make_macro(fail))
    }

    /// Writes `source` to a throwaway project as `src/Foo.sol`, registers `rule` as the single
    /// macro, and compiles, returning the compiler result so tests can inspect error messages.
    fn compile_source_with(source: &str, rule: Macro) -> eyre::Result<()> {
        let dir = tempfile::tempdir()?;
        let src_dir = dir.path().join("src");
        std::fs::create_dir(&src_dir)?;
        let sol_path = src_dir.join("Foo.sol");
        std::fs::write(&sol_path, source)?;

        let config = foundry_config::Config::with_root(dir.path());
        let project = config.project()?;

        let mut macros = crate::MacroRules::default();
        macros.rules.push(rule);

        crate::project_compiler::ProjectCompiler {
            project_root: project.root().to_path_buf(),
            print_names: false,
            print_sizes: false,
            bail: true,
            ignore_eip_3860: false,
            files: vec![sol_path],
        }
        .compile(&project, macros)
        .map(|_| ())
    }

    #[test]
    fn test_macro_error_attributed_to_macro() {
        let err = strip_ansi(&compile_with_macro(TEST_SOURCE_VALID, true).unwrap_err().to_string());
        // First line: macro attribution header.
        assert!(
            err.contains("error in code generated by macro 'insert_foo_fail':"),
            "expected named macro attribution, got:\n{err}"
        );
        // Arrow line: points to the `// #[insert_foo]` trigger comment at line 4, col 9.
        assert!(
            err.contains("Foo.sol:4:9:"),
            "expected --> line pointing to trigger comment at 4:9, got:\n{err}"
        );
        // Separator and framed source line showing the trigger comment.
        assert!(
            err.contains("  |\n4 |         // #[insert_foo]\n  |"),
            "expected framed trigger comment source line, got:\n{err}"
        );
    }

    #[test]
    fn test_source_error_line_is_remapped() {
        let err = compile_with_macro(TEST_SOURCE_INVALID, false).unwrap_err().to_string();
        assert!(
            !err.contains("error in code generated by macro"),
            "error was incorrectly attributed to macro:\n{err}"
        );
        assert!(
            err.contains("Foo.sol:5:"),
            "expected error remapped to original line 5, got:\n{err}"
        );
    }

    #[test]
    fn test_replace_error_attributed_to_macro() {
        let err = compile_source_with(TEST_SOURCE_REPLACE, replace_body).unwrap_err().to_string();
        let err = strip_ansi(&err);
        // The bad `return "bad";` lives on a line the replacement generated, so the error must be
        // attributed to the macro instead of being remapped to original source.
        assert!(
            err.contains("error in code generated by macro 'replace_body':"),
            "expected replacement error attributed to macro, got:\n{err}"
        );
        // Attribution points back to the `// #[replace_body]` trigger comment at line 4, col 9.
        assert!(
            err.contains("Foo.sol:4:9:"),
            "expected --> line pointing to trigger comment at 4:9, got:\n{err}"
        );
    }

    #[test]
    fn test_removal_remaps_downstream_error_line() {
        let err = compile_source_with(TEST_SOURCE_REMOVE, remove_block).unwrap_err().to_string();
        let err = strip_ansi(&err);
        // The error is in surviving original code, not macro-generated code.
        assert!(
            !err.contains("error in code generated by macro"),
            "removal error was incorrectly attributed to macro:\n{err}"
        );
        // `broken()` is on original line 9; the removal deletes four lines above it, so Solc sees
        // it on expanded line 5. The reported line must be remapped back to the original line 9.
        assert!(
            err.contains("Foo.sol:9:"),
            "expected error remapped to original line 9, got:\n{err}"
        );
        assert!(
            !err.contains("Foo.sol:5:"),
            "expected expanded line 5 to be remapped away, got:\n{err}"
        );
    }

    #[test]
    fn test_arrow_in_error_message_does_not_break_attribution() {
        let err = strip_ansi(
            &compile_source_with(TEST_SOURCE_VALID, insert_arrow_literal).unwrap_err().to_string(),
        );
        assert!(
            err.contains("error in code generated by macro 'insert_arrow_literal':"),
            "test failed",
        );
    }
}
