// Copyright (C) 2026, Ava Labs, Inc.
// See the file LICENSE for licensing terms.

#[cfg(test)]
use std::sync::Mutex;
use std::{fs, path::Path};

use foundry_compilers::artifacts::Error as SolcError;

use crate::{MacroOriginalLocation, MacroRules, span_utils::to_isize};

#[cfg(test)]
pub static TEST_COMPILER_OUTPUT: Mutex<Vec<String>> = Mutex::new(Vec::new());

const ARROW: &str = "-->";

/// Remaps compiler error line numbers in `e` from macro-expanded coordinates back to the
/// original source, or replaces the message with a macro-error notice if the error points
/// into macro-generated code.
///
/// `loc.file` is used directly as the lookup key because foundry-compilers calls
/// `strip_prefix(project_root)` on the compiler input *before* the preprocessor runs, so
/// the paths stored in `offset_adjustments` are in the same form (relative or absolute) as
/// the paths Solc reports in `source_location.file`.
pub fn correct_fmt_msg(macros: &MacroRules, e: &mut SolcError) {
    let Some(ref loc) = e.source_location else { return };
    let source = Path::new(&loc.file);
    let fmtd_msg = e.formatted_message.as_deref().unwrap_or("");
    let Some(primary) = parse_primary_location(source, fmtd_msg) else { return };

    // Check whether the primary location falls in macro-generated code before remapping.
    let attribution = {
        let adjustments = macros.offset_adjustments.lock().unwrap();
        adjustments
            .find_macro_adjustment(source, primary.line_num())
            .map(|adj| (adj.macro_name.clone(), adj.original_location.clone()))
    };
    if let Some((name, orig)) = attribution {
        let short = match &name {
            Some(name) => format!("error in code generated by macro '{}': {}", name, e.message),
            None => format!("error in macro-generated code: {}", e.message),
        };
        let fmt = match (name.as_deref(), orig.as_ref()) {
            (Some(_), Some(orig)) => format_macro_fmt_msg(orig, &short),
            _ => short.clone(),
        };
        e.message = short;
        e.formatted_message = Some(fmt);
    } else {
        e.formatted_message = Some(remap_fmt_msg(macros, source, fmtd_msg, primary));
    }
}

/// Parsed primary error location extracted from a formatted Solc error message.
enum PrimaryLocation {
    /// New-style: error description on the first line, `-->` location on a subsequent line.
    Arrow { line_num: isize, beginning: String, path: String, col: String, trailing: &'static str },
    /// Old-style: `path:LINE:COL: ErrorType: message` all on the first line.
    OldStyle { line_num: isize, source_str: String, after_line: String },
}

impl PrimaryLocation {
    fn line_num(&self) -> isize {
        match self {
            Self::Arrow { line_num, .. } | Self::OldStyle { line_num, .. } => *line_num,
        }
    }

    fn remapped(&self, remapped_line: usize) -> String {
        match self {
            Self::Arrow { beginning, path, col, trailing, .. } => {
                format!("{beginning}{ARROW} {path}:{remapped_line}:{col}{trailing}")
            }
            Self::OldStyle { source_str, after_line, .. } => {
                format!("{source_str}:{remapped_line}:{after_line}")
            }
        }
    }
}

/// Parses the primary error location out of a formatted Solc error message, returning a
/// [`PrimaryLocation`] that holds the already-decomposed components so they do not need
/// to be re-parsed during remapping.
fn parse_primary_location(source: &Path, fmtd_msg: &str) -> Option<PrimaryLocation> {
    let source_str = source.to_string_lossy();
    for line in fmtd_msg.lines() {
        if let Some((beginning, loc)) = line.split_once(ARROW) {
            let loc = loc.trim();
            // loc is "path/to/file.sol:LINE:COL:" — strip the structural trailing colon.
            let (without_trailing, trailing) = match loc.strip_suffix(':') {
                Some(s) => (s, ":"),
                None => (loc, ""),
            };
            let (rest, col) = without_trailing.rsplit_once(':')?;
            let (path, line_str) = rest.rsplit_once(':')?;
            return Some(PrimaryLocation::Arrow {
                line_num: line_str.parse().ok()?,
                beginning: beginning.to_string(),
                path: path.to_string(),
                col: col.to_string(),
                trailing,
            });
        }
        if line.starts_with(source_str.as_ref()) {
            let rest = line.strip_prefix(source_str.as_ref())?.strip_prefix(':')?;
            let (line_str, after_line) = rest.split_once(':')?;
            return Some(PrimaryLocation::OldStyle {
                line_num: line_str.parse().ok()?,
                source_str: source_str.into_owned(),
                after_line: after_line.to_string(),
            });
        }
    }
    None
}

/// Remaps all line numbers in `fmtd_msg` from macro-expanded coordinates back to the original
/// source. `primary` carries the already-parsed primary location so it is not re-parsed.
///
/// The caller is responsible for ensuring the primary location is not in macro-generated code.
fn remap_fmt_msg(
    macros: &MacroRules,
    source: &Path,
    fmtd_msg: &str,
    primary: PrimaryLocation,
) -> String {
    let remapped =
        macros.offset_adjustments.lock().unwrap().get_original_line(source, primary.line_num());
    let remapped_primary = primary.remapped(remapped);
    let is_old_style = matches!(primary, PrimaryLocation::OldStyle { .. });

    let mut lines = fmtd_msg.lines();
    let mut modified = String::new();

    if is_old_style {
        // First line is the primary location; consume and replace it.
        lines.next();
        modified.push_str(&remapped_primary);
        modified.push('\n');
    } else {
        // First line is the error description; copy lines until the --> line, replace it.
        let Some(first) = lines.next() else { return modified };
        modified.push_str(first);
        modified.push('\n');
        for line in lines.by_ref() {
            if line.contains(ARROW) {
                modified.push_str(&remapped_primary);
                modified.push('\n');
                break;
            }
            modified.push_str(line);
            modified.push('\n');
        }
    }

    // Remaining lines: remap line numbers in framed source context lines.
    for line in lines {
        modified.push_str(&remap_framed_line(macros, source, line));
        modified.push('\n');
    }
    modified
}

/// Extracts the line number from a framed source line (`LINE | ...`).
/// Returns `Some(LINE)` only when the prefix before `|` is a non-empty decimal number.
fn framed_line(line: &str) -> Option<usize> {
    let (prefix, _rest) = line.split_once('|')?;
    let trimmed = prefix.trim();
    if trimmed.is_empty() { None } else { trimmed.parse().ok() }
}

/// Remaps the line number in a framed source line, if one is present.
///
/// Returns the line unchanged if it has no line number (separator and caret lines like
/// `   |` and `   | ^^^`) or cannot be parsed.
fn remap_framed_line(macros: &MacroRules, source: &Path, line: &str) -> String {
    let Some(line_num) = framed_line(line) else { return line.to_string() };
    let adjustments = macros.offset_adjustments.lock().unwrap();
    let remapped = adjustments.get_original_line(source, to_isize(line_num));
    drop(adjustments);
    let (prefix, rest) = line.split_once('|').unwrap();
    let field_width = prefix.trim_end().len();
    format!("{remapped:>field_width$} |{rest}")
}

/// Formats a macro attribution error in the new-style Solc format:
///
/// ```text
/// error in code generated by macro 'name': <message>
///  --> /path/to/file.sol:LINE:COL:
///   |
/// N | <source line>
///   |
/// ```
///
/// Falls back to `short_msg` alone if the source line cannot be read.
fn format_macro_fmt_msg(orig: &MacroOriginalLocation, short_msg: &str) -> String {
    let source_line = fs::read_to_string(&orig.file).ok().and_then(|content| {
        content.lines().nth(orig.line.saturating_sub(1)).map(ToString::to_string)
    });
    let arrow = format!(" --> {}:{}:{}:", orig.file.display(), orig.line, orig.col);
    let width = orig.line.to_string().len();
    let sep = format!("{:width$} |", "");
    match source_line {
        Some(line_text) => {
            let framed = format!("{:>width$} | {}", orig.line, line_text);
            format!("{short_msg}\n{arrow}\n{sep}\n{framed}\n{sep}")
        }
        None => format!("{short_msg}\n{arrow}"),
    }
}

#[cfg(test)]
mod tests {
    use std::{fs, path::PathBuf};

    use foundry_compilers::error::Result as SolcResult;
    use solar::sema::{Gcx, hir::ContractKind};

    use crate::{
        Macro, MacroOriginalLocation, PreprocessingData,
        project_compiler::ProjectCompiler,
        span_utils::{file_offset, line_col_at},
    };

    /// Strips ANSI escape sequences from `s` so assertions can match plain text.
    fn strip_ansi(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut chars = s.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\x1b' && chars.peek() == Some(&'[') {
                chars.next(); // consume '['
                for c2 in chars.by_ref() {
                    if c2 == 'm' {
                        break;
                    }
                }
            } else {
                out.push(c);
            }
        }
        out
    }

    const TEST_SOURCE_VALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return 42; }
    }
    "#;

    const TEST_SOURCE_INVALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return "42"; }
    }
    "#;

    /// Source whose one-line function body is replaced by the `replace_body` macro with a
    /// multi-line block that introduces a type error. The `// #[replace_body]` trigger sits on
    /// line 4 (col 9) and the body to replace is on line 5.
    const TEST_SOURCE_REPLACE: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[replace_body]
        function original() internal pure returns (uint256) { return 1; }
    }
    "#;

    /// Source in which the `remove_block` macro deletes the `// #[remove_me]` comment and the
    /// entire `toRemove()` function (lines 4-7). The type error is in `broken()` on original
    /// line 9, which the removal shifts up to expanded line 5; error reporting must remap it back.
    const TEST_SOURCE_REMOVE: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[remove_me]
        function toRemove() internal pure returns (uint256) {
            return 1;
        }
        uint256 constant KEEP = 7;
        function broken() internal pure returns (uint256) { return "bad"; }
    }
    "#;

    fn make_macro(fail: bool) -> Macro {
        if fail { insert_foo_fail } else { insert_foo }
    }

    /// Returns the path of the source file that declares `library Foo`, if present.
    fn foo_source_path(data: &PreprocessingData<'_>) -> Option<PathBuf> {
        data.input
            .iter()
            .find(|(_, s)| s.content.as_str().contains("library Foo"))
            .map(|(p, _)| p.clone())
    }

    /// Replaces `original()`'s one-line body `{ return 1; }` with a multi-line block whose body
    /// returns a string literal (a `uint256` type error). Because the replacement spans more
    /// lines than it removes, the error lands *inside* the macro-generated span and must be
    /// attributed to the macro rather than remapped to original source.
    fn replace_body(_ctx: &Gcx, data: &mut PreprocessingData<'_>) -> SolcResult<()> {
        const BODY: &str = "{ return 1; }";
        let Some(path) = foo_source_path(data) else { return Ok(()) };
        let (range, loc) = {
            let content = data.input.get(&path).unwrap().content.as_str();
            let Some(start) = content.find(BODY) else { return Ok(()) };
            let trigger = content.find("// #[replace_body]").unwrap_or(start);
            let (line, col) = line_col_at(content, trigger);
            let loc = MacroOriginalLocation { file: path.clone(), line, col };
            (start..start.saturating_add(BODY.len()), loc)
        };
        let replacement = "{\n        return \"bad\";\n    }";
        data.entry(&path, replacement).with("replace_body", Some(loc)).replace(range);
        Ok(())
    }

    /// Removes the `// #[remove_me]` comment and the whole `toRemove()` function, deleting four
    /// lines and shifting everything below it up. Used to exercise line-number remapping of a
    /// compiler error that lives in surviving original source below a removal.
    fn remove_block(_ctx: &Gcx, data: &mut PreprocessingData<'_>) -> SolcResult<()> {
        let Some(path) = foo_source_path(data) else { return Ok(()) };
        let range = {
            let content = data.input.get(&path).unwrap().content.as_str();
            let Some(start) = content.find("        // #[remove_me]") else { return Ok(()) };
            let Some(end) = content.find("        uint256 constant KEEP") else { return Ok(()) };
            start..end
        };
        data.entry(&path, "").with("remove_block", None).replace(range);
        Ok(())
    }

    fn insert_foo(ctx: &Gcx, data: &mut PreprocessingData<'_>) -> SolcResult<()> {
        insert_in_foo(ctx, data, "insert_foo", false)
    }

    fn insert_foo_fail(ctx: &Gcx, data: &mut PreprocessingData<'_>) -> SolcResult<()> {
        insert_in_foo(ctx, data, "insert_foo_fail", true)
    }

    fn insert_in_foo(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
        macro_name: &str,
        fail: bool,
    ) -> SolcResult<()> {
        for contract in ctx.hir.contracts() {
            if contract.kind != ContractKind::Library || contract.name.name.as_str() != "Foo" {
                continue;
            }
            let Some(source) = ctx.sources.get(contract.source) else { continue };
            let Some(path) = source.file.name.as_real() else { continue };
            if !data.input.contains_key(path) {
                continue;
            }

            let start = file_offset(contract.span.lo().0, source.file.start_pos.0);
            let (after_open_brace, original_loc) = {
                let content = data.input.get(path).unwrap().content.as_str();
                let Some(rel) = content[start..].find('{') else { continue };
                // Use the trigger comment as the attribution location, falling back to the
                // library declaration if the comment is not found.
                let trigger_offset = content.find("// #[insert_foo]").unwrap_or(start);
                let (line, col) = line_col_at(content, trigger_offset);
                let loc = MacroOriginalLocation { file: path.to_path_buf(), line, col };
                (start.saturating_add(rel).saturating_add(1), loc)
            };

            let func = if fail {
                "\n    function inserted() internal pure returns (uint256) { return \"not a number\"; }\n"
            } else {
                "\n    function inserted() internal pure returns (uint256) { return 42; }\n"
            };
            data.entry(path, func).with(macro_name, Some(original_loc)).insert(after_open_brace);
        }
        Ok(())
    }

    fn compile_with_macro(source: &str, fail: bool) -> eyre::Result<()> {
        compile_source_with(source, make_macro(fail))
    }

    /// Writes `source` to a throwaway project as `src/Foo.sol`, registers `rule` as the single
    /// macro, and compiles, returning the compiler result so tests can inspect error messages.
    fn compile_source_with(source: &str, rule: Macro) -> eyre::Result<()> {
        let dir = tempfile::tempdir()?;
        let src_dir = dir.path().join("src");
        fs::create_dir(&src_dir)?;
        let sol_path = src_dir.join("Foo.sol");
        fs::write(&sol_path, source)?;

        let config = foundry_config::Config::with_root(dir.path());
        let project = config.project()?;

        let mut macros = crate::MacroRules::default();
        macros.rules.push(rule);

        ProjectCompiler {
            project_root: project.root().to_path_buf(),
            print_names: false,
            print_sizes: false,
            bail: true,
            ignore_eip_3860: false,
            files: vec![sol_path],
        }
        .compile(&project, macros)
        .map(|_| ())
    }

    #[test]
    fn test_macro_error_attributed_to_macro() {
        let err = strip_ansi(&compile_with_macro(TEST_SOURCE_VALID, true).unwrap_err().to_string());
        // First line: macro attribution header.
        assert!(
            err.contains("error in code generated by macro 'insert_foo_fail':"),
            "expected named macro attribution, got:\n{err}"
        );
        // Arrow line: points to the `// #[insert_foo]` trigger comment at line 4, col 9.
        assert!(
            err.contains("Foo.sol:4:9:"),
            "expected --> line pointing to trigger comment at 4:9, got:\n{err}"
        );
        // Separator and framed source line showing the trigger comment.
        assert!(
            err.contains("  |\n4 |         // #[insert_foo]\n  |"),
            "expected framed trigger comment source line, got:\n{err}"
        );
    }

    #[test]
    fn test_source_error_line_is_remapped() {
        let err = compile_with_macro(TEST_SOURCE_INVALID, false).unwrap_err().to_string();
        assert!(
            !err.contains("error in code generated by macro"),
            "error was incorrectly attributed to macro:\n{err}"
        );
        assert!(
            err.contains("Foo.sol:5:"),
            "expected error remapped to original line 5, got:\n{err}"
        );
    }

    #[test]
    fn test_replace_error_attributed_to_macro() {
        let err = compile_source_with(TEST_SOURCE_REPLACE, replace_body).unwrap_err().to_string();
        let err = strip_ansi(&err);
        // The bad `return "bad";` lives on a line the replacement generated, so the error must be
        // attributed to the macro instead of being remapped to original source.
        assert!(
            err.contains("error in code generated by macro 'replace_body':"),
            "expected replacement error attributed to macro, got:\n{err}"
        );
        // Attribution points back to the `// #[replace_body]` trigger comment at line 4, col 9.
        assert!(
            err.contains("Foo.sol:4:9:"),
            "expected --> line pointing to trigger comment at 4:9, got:\n{err}"
        );
    }

    #[test]
    fn test_removal_remaps_downstream_error_line() {
        let err = compile_source_with(TEST_SOURCE_REMOVE, remove_block).unwrap_err().to_string();
        let err = strip_ansi(&err);
        // The error is in surviving original code, not macro-generated code.
        assert!(
            !err.contains("error in code generated by macro"),
            "removal error was incorrectly attributed to macro:\n{err}"
        );
        // `broken()` is on original line 9; the removal deletes four lines above it, so Solc sees
        // it on expanded line 5. The reported line must be remapped back to the original line 9.
        assert!(
            err.contains("Foo.sol:9:"),
            "expected error remapped to original line 9, got:\n{err}"
        );
        assert!(
            !err.contains("Foo.sol:5:"),
            "expected expanded line 5 to be remapped away, got:\n{err}"
        );
    }
}
