// Copyright (C) 2026, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

use std::path::Path;

use foundry_compilers::artifacts::Error as SolcError;

use crate::{MacroOriginalLocation, MacroRules};

#[cfg(test)]
pub static TEST_COMPILER_OUTPUT: std::sync::Mutex<Vec<String>> = std::sync::Mutex::new(Vec::new());

const ARROW: &str = "-->";

/// Remaps compiler error line numbers in `e` from macro-expanded coordinates back to the
/// original source, or replaces the message with a macro-error notice if the error points
/// into macro-generated code.
///
/// `loc.file` is used directly as the lookup key because foundry-compilers calls
/// `strip_prefix(project_root)` on the compiler input *before* the preprocessor runs, so
/// the paths stored in `offset_adjustments` are in the same form (relative or absolute) as
/// the paths Solc reports in `source_location.file`.
pub fn correct_fmt_msg(macros: &MacroRules, e: &mut SolcError) {
    let Some(ref loc) = e.source_location else { return };
    let source = Path::new(&loc.file);
    let fmtd_msg = e.formatted_message.as_deref().unwrap_or("");
    let Some(primary) = parse_primary_location(source, fmtd_msg) else { return };

    // Check whether the primary location falls in macro-generated code before remapping.
    let attribution = {
        let adjustments = macros.offset_adjustments.lock().unwrap();
        adjustments
            .find_macro_adjustment(source, primary.line_num())
            .map(|adj| (adj.macro_name.clone(), adj.original_location.clone()))
    };
    if let Some((name, orig)) = attribution {
        let short = match &name {
            Some(name) => format!("error in code generated by macro '{}': {}", name, e.message),
            None => format!("error in macro-generated code: {}", e.message),
        };
        let fmt = match (name.as_deref(), orig.as_ref()) {
            (Some(_), Some(orig)) => format_macro_fmt_msg(orig, &short),
            _ => short.clone(),
        };
        e.message = short;
        e.formatted_message = Some(fmt);
    } else {
        e.formatted_message = Some(remap_fmt_msg(macros, source, fmtd_msg, primary));
    }
}

/// Parsed primary error location extracted from a formatted Solc error message.
enum PrimaryLocation {
    /// New-style: error description on the first line, `-->` location on a subsequent line.
    Arrow { line_num: isize, beginning: String, path: String, col: String, trailing: &'static str },
    /// Old-style: `path:LINE:COL: ErrorType: message` all on the first line.
    OldStyle { line_num: isize, source_str: String, after_line: String },
}

impl PrimaryLocation {
    fn line_num(&self) -> isize {
        match self {
            Self::Arrow { line_num, .. } | Self::OldStyle { line_num, .. } => *line_num,
        }
    }

    /// The primary column, as reported by Solc, in expanded-source coordinates.
    fn col(&self) -> &str {
        match self {
            Self::Arrow { col, .. } => col,
            // `after_line` is "COL: ErrorType: message"; the column is the leading segment.
            Self::OldStyle { after_line, .. } => {
                after_line.split_once(':').map_or(after_line.as_str(), |(col, _)| col)
            }
        }
    }

    /// Rebuilds the location line with the remapped line number, substituting `remapped_col` for
    /// the column when it is `Some` and leaving the original column text in place otherwise.
    fn remapped(&self, remapped_line: usize, remapped_col: Option<usize>) -> String {
        match self {
            Self::Arrow { beginning, path, col, trailing, .. } => {
                let col = remapped_col.map_or_else(|| col.clone(), |c| c.to_string());
                format!("{beginning}{ARROW} {path}:{remapped_line}:{col}{trailing}")
            }
            Self::OldStyle { source_str, after_line, .. } => {
                // Replace the leading column segment, keep the "ErrorType: message" tail.
                let after = match (remapped_col, after_line.split_once(':')) {
                    (Some(c), Some((_, tail))) => format!("{c}:{tail}"),
                    _ => after_line.clone(),
                };
                format!("{source_str}:{remapped_line}:{after}")
            }
        }
    }
}

/// Parses the primary error location out of a formatted Solc error message, returning a
/// [`PrimaryLocation`] that holds the already-decomposed components so they do not need
/// to be re-parsed during remapping.
fn parse_primary_location(source: &Path, fmtd_msg: &str) -> Option<PrimaryLocation> {
    let source_str = source.to_string_lossy();
    for line in fmtd_msg.lines() {
        if let Some((beginning, loc)) = line.split_once(ARROW) {
            let loc = loc.trim();
            // loc is "path/to/file.sol:LINE:COL:" — strip the structural trailing colon.
            let (without_trailing, trailing) = match loc.strip_suffix(':') {
                Some(s) => (s, ":"),
                None => (loc, ""),
            };
            let (rest, col) = without_trailing.rsplit_once(':')?;
            let (path, line_str) = rest.rsplit_once(':')?;
            return Some(PrimaryLocation::Arrow {
                line_num: line_str.parse().ok()?,
                beginning: beginning.to_string(),
                path: path.to_string(),
                col: col.to_string(),
                trailing,
            });
        }
        if line.starts_with(source_str.as_ref()) {
            let rest = line.strip_prefix(source_str.as_ref())?.strip_prefix(':')?;
            let (line_str, after_line) = rest.split_once(':')?;
            return Some(PrimaryLocation::OldStyle {
                line_num: line_str.parse().ok()?,
                source_str: source_str.into_owned(),
                after_line: after_line.to_string(),
            });
        }
    }
    None
}

/// Remaps all line numbers in `fmtd_msg` from macro-expanded coordinates back to the original
/// source. `primary` carries the already-parsed primary location so it is not re-parsed.
///
/// The caller is responsible for ensuring the primary location is not in macro-generated code.
fn remap_fmt_msg(
    macros: &MacroRules,
    source: &Path,
    fmtd_msg: &str,
    primary: PrimaryLocation,
) -> String {
    let (remapped, remapped_col) = {
        let adjustments = macros.offset_adjustments.lock().unwrap();
        let line = adjustments.get_original_line(source, primary.line_num());
        let col = primary
            .col()
            .trim()
            .parse::<isize>()
            .ok()
            .map(|c| adjustments.get_original_col(source, line, c));
        (line, col)
    };
    let remapped_primary = primary.remapped(remapped, remapped_col);
    let is_old_style = matches!(primary, PrimaryLocation::OldStyle { .. });

    let mut lines = fmtd_msg.lines();
    let mut modified = String::new();

    if is_old_style {
        // First line is the primary location; consume and replace it.
        lines.next();
        modified.push_str(&remapped_primary);
        modified.push('\n');
    } else {
        // First line is the error description; copy lines until the --> line, replace it.
        let Some(first) = lines.next() else { return modified };
        modified.push_str(first);
        modified.push('\n');
        for line in lines.by_ref() {
            if line.contains(ARROW) {
                modified.push_str(&remapped_primary);
                modified.push('\n');
                break;
            }
            modified.push_str(line);
            modified.push('\n');
        }
    }

    // Remaining lines: remap line numbers in framed source context lines.
    for line in lines {
        modified.push_str(&remap_framed_line(macros, source, line));
        modified.push('\n');
    }
    modified
}

/// Extracts the line number from a framed source line (`LINE | ...`).
/// Returns `Some(LINE)` only when the prefix before `|` is a non-empty decimal number.
fn framed_line(line: &str) -> Option<usize> {
    let (prefix, _rest) = line.split_once('|')?;
    let trimmed = prefix.trim();
    if trimmed.is_empty() { None } else { trimmed.parse().ok() }
}

/// Remaps the line number in a framed source line, if one is present.
///
/// Returns the line unchanged if it has no line number (separator and caret lines like
/// `   |` and `   | ^^^`) or cannot be parsed.
fn remap_framed_line(macros: &MacroRules, source: &Path, line: &str) -> String {
    let Some(line_num) = framed_line(line) else { return line.to_string() };
    let adjustments = macros.offset_adjustments.lock().unwrap();
    let remapped = adjustments.get_original_line(source, line_num as isize);
    drop(adjustments);
    let (prefix, rest) = line.split_once('|').unwrap();
    let field_width = prefix.trim_end().len();
    format!("{remapped:>field_width$} |{rest}")
}

/// Formats a macro attribution error in the new-style Solc format:
///
/// ```text
/// error in code generated by macro 'name': <message>
///  --> /path/to/file.sol:LINE:COL:
///   |
/// N | <source line>
///   |
/// ```
///
/// Falls back to `short_msg` alone if the source line cannot be read.
fn format_macro_fmt_msg(orig: &MacroOriginalLocation, short_msg: &str) -> String {
    let source_line = std::fs::read_to_string(&orig.file)
        .ok()
        .and_then(|content| content.lines().nth(orig.line - 1).map(|l| l.to_string()));
    let arrow = format!(" --> {}:{}:{}:", orig.file.display(), orig.line, orig.col);
    let width = orig.line.to_string().len();
    let sep = format!("{:width$} |", "");
    match source_line {
        Some(line_text) => {
            let framed = format!("{:>width$} | {}", orig.line, line_text);
            format!("{short_msg}\n{arrow}\n{sep}\n{framed}\n{sep}")
        }
        None => format!("{short_msg}\n{arrow}"),
    }
}

#[cfg(test)]
mod tests {
    use solar::sema::{Gcx, hir::ContractKind};

    use crate::{Macro, MacroOriginalLocation, PreprocessingData};

    /// Strips ANSI escape sequences from `s` so assertions can match plain text.
    fn strip_ansi(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut chars = s.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\x1b' && chars.peek() == Some(&'[') {
                chars.next(); // consume '['
                for c2 in chars.by_ref() {
                    if c2 == 'm' {
                        break;
                    }
                }
            } else {
                out.push(c);
            }
        }
        out
    }

    const TEST_SOURCE_VALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return 42; }
    }
    "#;

    const TEST_SOURCE_INVALID: &str = r#"
    pragma solidity ^0.8.30;
    library Foo {
        // #[insert_foo]
        function original() internal pure returns (uint256) { return "42"; }
    }
    "#;

    fn make_macro(fail: bool) -> Macro {
        if fail { insert_foo_fail } else { insert_foo }
    }

    fn insert_foo(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        insert_in_foo(ctx, data, "insert_foo", false)
    }

    fn insert_foo_fail(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
    ) -> foundry_compilers::error::Result<()> {
        insert_in_foo(ctx, data, "insert_foo_fail", true)
    }

    fn insert_in_foo(
        ctx: &Gcx,
        data: &mut PreprocessingData<'_>,
        macro_name: &str,
        fail: bool,
    ) -> foundry_compilers::error::Result<()> {
        for contract in ctx.hir.contracts() {
            if contract.kind != ContractKind::Library || contract.name.name.as_str() != "Foo" {
                continue;
            }
            let Some(source) = ctx.sources.get(contract.source) else { continue };
            let Some(path) = source.file.name.as_real() else { continue };
            if !data.input.contains_key(path) {
                continue;
            }

            let start = (contract.span.lo().0 - source.file.start_pos.0) as usize;
            let (after_open_brace, original_loc) = {
                let content = data.input.get(path).unwrap().content.as_str();
                let Some(rel) = content[start..].find('{') else { continue };
                // Use the trigger comment as the attribution location, falling back to the
                // library declaration if the comment is not found.
                let trigger_offset = content.find("// #[insert_foo]").unwrap_or(start);
                let before = &content[..trigger_offset];
                let line = before.bytes().filter(|&b| b == b'\n').count() + 1;
                let col = trigger_offset - before.rfind('\n').map_or(0, |i| i + 1) + 1;
                let loc = MacroOriginalLocation { file: path.to_path_buf(), line, col };
                (start + rel + 1, loc)
            };

            let func = if fail {
                "\n    function inserted() internal pure returns (uint256) { return \"not a number\"; }\n"
            } else {
                "\n    function inserted() internal pure returns (uint256) { return 42; }\n"
            };
            data.entry(path, func).with(macro_name, Some(original_loc)).insert(after_open_brace);
        }
        Ok(())
    }

    fn compile_with_macro(source: &str, fail: bool) -> eyre::Result<()> {
        let dir = tempfile::tempdir()?;
        let src_dir = dir.path().join("src");
        std::fs::create_dir(&src_dir)?;
        let sol_path = src_dir.join("Foo.sol");
        std::fs::write(&sol_path, source)?;

        let config = foundry_config::Config::with_root(dir.path());
        let project = config.project()?;

        let mut macros = crate::MacroRules::default();
        macros.rules.push(make_macro(fail));

        crate::project_compiler::ProjectCompiler {
            project_root: project.root().to_path_buf(),
            print_names: false,
            print_sizes: false,
            bail: true,
            ignore_eip_3860: false,
            files: vec![sol_path],
        }
        .compile(&project, macros)
        .map(|_| ())
    }

    #[test]
    fn test_macro_error_attributed_to_macro() {
        let err = strip_ansi(&compile_with_macro(TEST_SOURCE_VALID, true).unwrap_err().to_string());
        // First line: macro attribution header.
        assert!(
            err.contains("error in code generated by macro 'insert_foo_fail':"),
            "expected named macro attribution, got:\n{err}"
        );
        // Arrow line: points to the `// #[insert_foo]` trigger comment at line 4, col 9.
        assert!(
            err.contains("Foo.sol:4:9:"),
            "expected --> line pointing to trigger comment at 4:9, got:\n{err}"
        );
        // Separator and framed source line showing the trigger comment.
        assert!(
            err.contains("  |\n4 |         // #[insert_foo]\n  |"),
            "expected framed trigger comment source line, got:\n{err}"
        );
    }

    #[test]
    fn test_source_error_line_is_remapped() {
        let err = compile_with_macro(TEST_SOURCE_INVALID, false).unwrap_err().to_string();
        assert!(
            !err.contains("error in code generated by macro"),
            "error was incorrectly attributed to macro:\n{err}"
        );
        assert!(
            err.contains("Foo.sol:5:"),
            "expected error remapped to original line 5, got:\n{err}"
        );
    }

    /// Builds a `MacroRules` carrying a single inline `library` -> `contract` replacement on line
    /// 3 (a single-line edit that shifts columns right by one from column 1 onward).
    fn macros_with_inline_replace() -> crate::MacroRules {
        use std::path::PathBuf;

        use crate::span_utils::Adjustment;

        let macros = crate::MacroRules::default();
        macros.offset_adjustments.lock().unwrap().push((
            PathBuf::from("Foo.sol"),
            Adjustment {
                original_offset: 4,
                original_line: 3,
                original_col: 1,
                delta_offset: 1,
                delta_line: 0,
                delta_col: 1,
                macro_name: None,
                original_location: None,
            },
        ));
        macros
    }

    #[test]
    fn test_arrow_column_is_remapped() {
        use std::path::Path;

        let macros = macros_with_inline_replace();
        let source = Path::new("Foo.sol");
        let fmtd = "Error: identifier not found\n --> Foo.sol:3:10:\n  |\n3 | contract Foo {\n  |          ^^^\n";

        let primary = super::parse_primary_location(source, fmtd).expect("should parse location");
        let out = super::remap_fmt_msg(&macros, source, fmtd, primary);
        assert!(
            out.contains(" --> Foo.sol:3:9:"),
            "expected column remapped from 10 to 9, got:\n{out}"
        );
    }

    #[test]
    fn test_old_style_column_is_remapped() {
        use std::path::Path;

        let macros = macros_with_inline_replace();
        let source = Path::new("Foo.sol");
        let fmtd = "Foo.sol:3:10: Error: identifier not found";

        let primary = super::parse_primary_location(source, fmtd).expect("should parse location");
        let out = super::remap_fmt_msg(&macros, source, fmtd, primary);
        assert!(
            out.contains("Foo.sol:3:9: Error: identifier not found"),
            "expected column remapped from 10 to 9, got:\n{out}"
        );
    }
}
