// Copyright (C) 2026, Ava Labs, Inc.
// See the file LICENSE for licensing terms.

// Pedantic lints target the production code; the test modules are held to the
// default `clippy::all` bar.
#![cfg_attr(test, allow(clippy::pedantic))]

mod build;
mod coverage;
pub mod display;
mod errors;
mod lockfile;
mod project_compiler;
mod snapshot;
mod span_utils;
mod test;
pub mod testing;

use std::{
    collections::HashSet,
    fmt::{self, Debug, Formatter},
    mem,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
};

use clap::{FromArgMatches, Parser, Subcommand};
use forge::{
    args::{run_command, setup},
    cmd::build::BuildArgs,
    opts::{Forge, ForgeSubcommand},
};
use foundry_cli::{opts::GlobalArgs, utils::LoadConfig};
use foundry_common::{
    errors::convert_solar_errors,
    version::{LONG_VERSION, SHORT_VERSION},
};
use foundry_compilers::{
    Compiler, ProjectPathsConfig, SourceParser,
    artifacts::{SolcLanguage, Sources},
    error::Result as SolcResult,
    multi::{MultiCompiler, MultiCompilerInput},
    project::Preprocessor,
    resolver::parse::SolParser,
    solc::SolcCompiler,
};
use solar::{
    interface::Span,
    sema::{Gcx, hir::SourceId},
};

pub use crate::span_utils::{
    AdjustmentEntry, EditInfo, MacroOriginalLocation, file_offset, line_col_at,
};
use crate::{span_utils::OffsetAdjustment, test::TestArgs};

#[derive(Parser)]
#[command(
    name = "reforge",
    version = SHORT_VERSION,
    long_version = LONG_VERSION,
    about = "A tool for combining with Forge with macro expansions in Solidity.",
)]
pub struct Reforge {
    #[command(flatten)]
    pub global: GlobalArgs,

    #[arg(long, help = "Disable macro expansion.")]
    pub disable_macros: bool,
    /// Print macro-expanded sources whose paths (relative to the build root)
    /// match this glob pattern, then exit. Only supported with the `build`
    /// subcommand.
    #[arg(long, value_name = "GLOB")]
    pub display: Option<String>,

    #[command(subcommand)]
    pub forge: ForgeCommand,
}

pub enum ForgeCommand {
    Intercept(TestArgs),
    Forward(Forge),
}

impl FromArgMatches for ForgeCommand {
    fn from_arg_matches(matches: &clap::ArgMatches) -> Result<Self, clap::Error> {
        if let Some(("test" | "t", sub_matches)) = matches.subcommand() {
            Ok(ForgeCommand::Intercept(TestArgs::from_arg_matches(sub_matches)?))
        } else {
            // With global = true, clap stores global args (verbosity, quiet, etc.) in the
            // subcommand matches, not in the root matches. Parse GlobalArgs from there.
            let global = match matches.subcommand() {
                Some((_, sub_matches)) => GlobalArgs::from_arg_matches(sub_matches)?,
                None => GlobalArgs::default(),
            };
            let cmd = ForgeSubcommand::from_arg_matches(matches)?;
            Ok(ForgeCommand::Forward(Forge { global, cmd }))
        }
    }

    fn from_arg_matches_mut(matches: &mut clap::ArgMatches) -> Result<Self, clap::Error> {
        Self::from_arg_matches(matches)
    }

    fn update_from_arg_matches(&mut self, matches: &clap::ArgMatches) -> Result<(), clap::Error> {
        *self = Self::from_arg_matches(matches)?;
        Ok(())
    }

    fn update_from_arg_matches_mut(
        &mut self,
        matches: &mut clap::ArgMatches,
    ) -> Result<(), clap::Error> {
        self.update_from_arg_matches(matches)
    }
}

impl Subcommand for ForgeCommand {
    fn augment_subcommands(cmd: clap::Command) -> clap::Command {
        ForgeSubcommand::augment_subcommands(cmd)
    }

    fn augment_subcommands_for_update(cmd: clap::Command) -> clap::Command {
        ForgeSubcommand::augment_subcommands_for_update(cmd)
    }

    fn has_subcommand(name: &str) -> bool {
        ForgeSubcommand::has_subcommand(name)
    }
}

/// A macro rule function: takes the global compiler context and mutable preprocessing data,
/// and returns a result.
pub type Macro = fn(ctx: &Gcx, data: &mut PreprocessingData<'_>) -> SolcResult<()>;

/// The data passed to implementations of the `Preprocessor` trait.
#[derive(Debug)]
pub struct PreprocessingData<'pre> {
    /// The source files being compiled
    pub input: &'pre mut Sources,
    /// The root of the project being compiled.
    pub root_dir: &'pre Path,
    /// Where to find the sources
    pub src_dir: &'pre Path,
    /// Mocks generated by foundry/forge.
    pub mocks: &'pre mut HashSet<PathBuf>,
    /// Rules that use HIR spans should call
    /// [`PreprocessingData::adjusted_offset`] to compensate for prior insertions/deletions.
    pub offset_adjustments: OffsetAdjustment,
}

impl<'pre> PreprocessingData<'pre> {
    #[must_use]
    pub fn adjusted_offset(&self, path: &Path, original_offset: usize) -> usize {
        self.offset_adjustments.adjusted_offset(path, original_offset)
    }

    /// Returns a builder for inserting or replacing text in `path`.
    ///
    /// Call [`.with(name, loc)`](AdjustmentEntry::with) on the returned builder before
    /// [`.insert()`](AdjustmentEntry::insert) or [`.replace()`](AdjustmentEntry::replace) to
    /// attach macro attribution so that compiler errors in the generated code are reported with
    /// the macro name and (optionally) the original triggering location.
    pub fn entry<'a>(&'a mut self, path: &'a Path, text: &'a str) -> AdjustmentEntry<'a>
    where
        'pre: 'a,
    {
        AdjustmentEntry::new(path, text, &mut *self.input, &mut self.offset_adjustments)
    }
}

/// A collection of macro rules which will be executed as a `Preprocessor`
#[derive(Default, Clone)]
pub struct MacroRules {
    pub rules: Vec<Macro>,
    pub(crate) preprocessed_sources: Arc<Mutex<Option<Sources>>>,
    pub(crate) offset_adjustments: Arc<Mutex<OffsetAdjustment>>,
}

impl Debug for MacroRules {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.debug_struct("MacroRules").field("rules", &"<functions>").finish()
    }
}

impl MacroRules {
    /// Runs the CLI. This should be used by downstream users as the main entry point of their
    /// program.
    ///
    /// # Errors
    ///
    /// Returns an error if the global Foundry setup fails, or if the dispatched
    /// subcommand does.
    ///
    /// # Panics
    ///
    /// Panics if the arguments cannot be re-parsed after the `--display` glob is
    /// stripped, which would indicate a bug in the argument rewriting.
    pub fn run(self) -> eyre::Result<()> {
        setup()?;
        let args = Reforge::parse();

        match args.forge {
            ForgeCommand::Intercept(test_args) => {
                test_args.global.init()?;
                let macros = if args.disable_macros {
                    MacroRules::default()
                } else if self.rules.is_empty() {
                    tracing::info!("No macros rules present, skipping macro expansion.");
                    println!("No macros rules present, skipping macro expansion.");
                    MacroRules::default()
                } else {
                    self
                };
                let runtime = test_args.global.tokio_runtime();
                runtime.block_on(test::test(test_args, macros))
            }
            ForgeCommand::Forward(forge) => {
                forge.global.init()?;

                if let Some(glob) = args.display {
                    let ForgeSubcommand::Build(build_args) = forge.cmd else {
                        panic!("--display is only supported with the `build` subcommand");
                    };
                    let (root, sources) = self.expand_for_display(build_args)?;
                    return display::display_sources(&root, &glob, &sources);
                }

                if !args.disable_macros {
                    if self.rules.is_empty() {
                        tracing::info!("No macros rules present, skipping macro expansion.");
                        println!("No macros rules present, skipping macro expansion.");
                    } else {
                        let Forge { global, cmd } = forge;
                        return match cmd {
                            ForgeSubcommand::Build(build_args) => {
                                if build_args.build.dynamic_test_linking {
                                    tracing::warn!(
                                        "Dynamic linking is not supported with macros expansion, skipping."
                                    );
                                    println!(
                                        "Dynamic linking is not supported with macros expansion, skipping."
                                    );
                                }
                                global.block_on(build::build(build_args, self))
                            }
                            // Foundry's `GasSnapshotArgs` hides its fields, so we re-parse the
                            // process arguments into reforge's own mirror of the struct.
                            ForgeSubcommand::Snapshot(_) => {
                                let snapshot_args = snapshot::parse_from_env();
                                global.block_on(snapshot_args.run(self))
                            }
                            // Foundry's `CoverageArgs` hides its fields, so we re-parse the
                            // process arguments into reforge's own mirror of the struct.
                            ForgeSubcommand::Coverage(_) => {
                                let coverage_args = coverage::parse_from_env();
                                global.block_on(coverage_args.run(self))
                            }
                            cmd => run_command(Forge { global, cmd }),
                        };
                    }
                }

                run_command(forge)
            }
        }
    }

    fn expand_for_display(&self, build_args: BuildArgs) -> eyre::Result<(PathBuf, Sources)> {
        let config = build_args.load_config()?;
        let project = config.project()?;
        let root = project.root().to_path_buf();
        let paths = project.paths.clone().with_language::<SolcLanguage>();
        // Read only the project's own source files (not lib/) so that solar's HIR lowering
        // succeeds.  Import resolution is handled by SolParser's remapping-aware file loader.
        let sources = project.paths.read_input_files()?;
        let expanded =
            testing::expand_macros_with_sources(sources, &root, Some(&paths), &self.rules)?;
        Ok((root, expanded))
    }
}

impl Preprocessor<SolcCompiler> for MacroRules {
    fn preprocess(
        &self,
        _compiler: &SolcCompiler,
        input: &mut <SolcCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<SolcCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> SolcResult<()> {
        let mut compiler = SolParser::new(paths.with_language_ref()).into_compiler();
        compiler.enter_mut(|compiler| -> SolcResult<()> {
            let mut pcx = compiler.parse();

            // Add the sources into the context.
            // Include all sources in the source map so as to not re-load them from disk, but only
            // parse and preprocess tests and scripts.
            let sources = &mut input.input.sources;
            for (path, source) in sources.iter() {
                if let Ok(src_file) = compiler
                    .sess()
                    .source_map()
                    .new_source_file(path.clone(), source.content.as_str())
                {
                    pcx.add_file(src_file);
                }
            }

            // Parse and preprocess.
            pcx.parse();
            // lower_asts() may return Break when the pre-expansion code references symbols that
            // macros will inject (expected). Run macro rules regardless — Solar's HIR is
            // partially built and struct/item definitions that rules need are present.
            let _ = compiler.lower_asts();
            let mut prepocessing_data = PreprocessingData {
                input: &mut input.input.sources,
                root_dir: &paths.root,
                src_dir: &paths.paths_relative().sources,
                mocks,
                offset_adjustments: OffsetAdjustment::default(),
            };
            let gcx = compiler.gcx();
            for rule in &self.rules {
                rule(&gcx, &mut prepocessing_data)?;
            }
            *self.preprocessed_sources.lock().unwrap() = Some(prepocessing_data.input.clone());
            *self.offset_adjustments.lock().unwrap() =
                mem::take(&mut prepocessing_data.offset_adjustments);
            Ok(())
        })?;

        // Solar diagnostics during preprocessing are intentionally ignored: the source passed to
        // Solar is the original, unmodified code, so references to symbols that macros will inject
        // are expected to be unresolved at this stage.
        let _ = convert_solar_errors(compiler.dcx());

        Ok(())
    }
}

impl Preprocessor<MultiCompiler> for MacroRules {
    fn preprocess(
        &self,
        compiler: &MultiCompiler,
        input: &mut <MultiCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<MultiCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> SolcResult<()> {
        // Preprocess only Solc compilers.
        let MultiCompilerInput::Solc(input) = input else {
            return Ok(());
        };

        let Some(solc) = &compiler.solc else {
            return Ok(());
        };

        let paths = paths.clone().with_language::<SolcLanguage>();
        self.preprocess(solc, input, &paths, mocks)
    }
}

/// Returns the comment immediately preceding the given HIR item, if any.
///
/// Walks backward from `span` in the source text and collects contiguous non-empty lines
/// that form a comment block (`//` or `/* ... */`). Returns `None` if the preceding
/// non-whitespace content is not a comment, or if the item's source is not in `data.input`.
#[must_use]
pub fn get_comment(
    ctx: &Gcx,
    source_id: SourceId,
    span: Span,
    data: &PreprocessingData<'_>,
) -> Option<String> {
    let source = ctx.sources.get(source_id)?;
    let path = source.file.name.as_real()?;
    let source_text = data.input.get(path)?.content.as_str();
    let original_offset = file_offset(span.lo().0, source.file.start_pos.0);
    let adjusted = data.adjusted_offset(path, original_offset);
    // Walk back to the start of the line
    let line_start = source_text[..adjusted].rfind('\n').map_or(0, |i| i.saturating_add(1));
    let before = &source_text[..line_start];
    let mut comment_block = String::new();
    let mut in_block_comment = false;
    // Walk backward over whitespace/newlines to find the preceding line(s)
    for l in before.lines().rev() {
        let trimmed = l.trim();
        if trimmed.is_empty() {
            break;
        }
        if in_block_comment {
            comment_block.insert_str(0, l);
            if trimmed.starts_with("/*") {
                break;
            }
        } else if trimmed.starts_with("//") {
            comment_block.insert_str(0, l);
        } else if trimmed.ends_with("*/") {
            in_block_comment = true;
            comment_block.insert_str(0, l);
            if trimmed.starts_with("/*") {
                break;
            }
        } else {
            break;
        }
    }
    let trimmed = comment_block.trim_start();
    if trimmed.starts_with("//") || trimmed.starts_with("/*") { Some(comment_block) } else { None }
}
